module App
  DEFAULT_TIME_ZONE = 'Australia/Brisbane'
  SUBSCRIPTION_TRIAL_DAYS = 10
  DEFAULT_CURRENCY = 'AUD'
  DEFAULT_COUNTRY = 'AU'
  COUNTRY_AUSTRALIA = 'AU'
  SUPPORT_COUNTRIES = ['AU', 'NZ', 'US', 'UK']
  DEFAULT_LOCALE = 'en-AU'
  SUPPORT_LOCALES = {'US' => 'en-US', 'AU' => 'en-AU', 'NZ' => 'en-NZ', 'GB' => 'en-GB'}
  RECAPTCHA_ENABLE = ['true', '1', 1].include?(ENV['RECAPTCHA_ENABLE'])
  MAX_ATTENDANCE_PROOFS = 3
  MEDIPASS_ENABLE = ['true', '1', 1].include?(ENV['MEDIPASS_ENABLE'])
  MAX_USER_API_KEYS = 3

  MAX_BULK_CREATE_INVOICES = 50
  MAX_BULK_CREATE_PAYMENTS = 50

  EMAIL_DELIVERY_TRACKING_FIELD_NAME = 'communication_tracking_id'

  DEFAULT_AVAILABILITY_SUBTYPES = [
    'Meeting', 'Annual leave'
  ]

  MINIMUM_SUBSCRIPTION_FEE = 15

  PAGE_SIZE_OPTIONS = [50, 100]
  DEFAULT_PAGE_SIZE = 50
end
