json.patients do
  json.array!(
    @patients,
      :id,
      :first_name,
      :last_name,
      :full_name,
      :email,
      :phone,
      :mobile,
      :dob,
      :gender,
      :full_address,
      :short_address,
      :address1,
      :address2,
      :city,
      :state,
      :postcode,
      :country,
      :latitude,
      :longitude,
      :important_notification,
      :mobile_formated,
      :phone_formated,
      :reminder_enable
    )
end
